### ISSUE TITLE
Updates Bug

### ISSUE THREAD

**Issue by ncalcott** [everythingtype/calcott#40] opened 2014-06-18 14:07 UTC
So, this is intermittent, and I can't tell you when it'll happen, but one of the update boxes (usually the twitter one) will occasionally appear blank on page load.  I've been able to replicate it by hitting reload repeatedly.  I'm fine with the occasional error with the connection with the twitter API (very occasional, if possible), but I'd love to have an error message, like "Twitter currently unavailable," or something similar.

Also, I've heard from a couple of friends that they're seeing NaN messages on those update boxes occasionally, but can't replicate.

**Comment by ncalcott** [comment] 2016-05-29 06:16
So, we seem to have figured out that it's a bug in Safari and works totally fine in chrome.

**Comment by halfempty** [comment] 2016-08-16 01:25
This is a duplicate of #51

**Closed by halfempty** 2016-08-16 01:25 UTC
